// Login
export const USER_LOGIN = 'USER_LOGIN'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'
export const FETCH_SESSION = 'FETCH_SESSION'

export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'
export const FETCH_MEMBER = 'FETCH_MEMBER'

export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const FETCH_VILLA_LIST = 'FETCH_VILLA_LIST'
export const FETCH_VILLA = 'FETCH_VILLA'

export const FETCH_LIKED_PRODUCT_LIST = 'FETCH_LIKED_PRODUCT_LIST'
export const FETCH_PRODUCT_INFO = 'FETCH_PRODUCT_INFO'

// Villa
// export const FETCH_VILLA_LIST = 'FETCH_VILLA_LIST'

//크롤링
export const CRAWL_START = 'CRAWL_START'
