// Login
export const USER_LOGIN = 'USER_LOGIN'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'
export const FETCH_SESSION = 'FETCH_SESSION'

export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'
export const FETCH_MEMBER = 'FETCH_MEMBER'

export const FETCH_VILLA_LIST = 'FETCH_VILLA_LIST'
export const FETCH_VILLA = 'FETCH_VILLA'
export const FETCH_ONEROOM_LIST = 'FETCH_ONEROOM_LIST'
export const FETCH_ONEROOM = 'FETCH_ONEROOM'
export const FETCH_OFFICETEL_LIST = 'FETCH_OFFICETEL_LIST'
export const FETCH_OFFICETEL = 'FETCH_OFFICETEL'

export const FETCH_LIKED_PRODUCT_LIST = 'FETCH_LIKED_PRODUCT_LIST'
export const FETCH_PRODUCT_INFO = 'FETCH_PRODUCT_INFO'

export const FETCH_AGENT_VILLA = 'FETCH_AGENT_VILLA'
export const FETCH_AGENT_ONEROOM = 'FETCH_AGENT_ONEROOM'
export const FETCH_AGENT_OFFICETEL = 'FETCH_AGENT_OFFICETEL'

export const FETCH_GONGZI_LIST = 'FETCH_GONGZI_LIST'
export const FETCH_GONGZI = 'FETCH_GONGZI'



//크롤링
export const CRAWL_START = 'CRAWL_START'
