// Login
export const USER_LOGIN = 'USER_LOGIN'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'
export const FETCH_SESSION = 'FETCH_SESSION'

export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'
export const FETCH_MEMBER = 'FETCH_MEMBER'